### ISSUE TITLE
List of bugs related to new shader decompiler

### ISSUE THREAD

**Issue by kd-11** [RPCS3/rpcs3#1899]
This is a tracker for issues related to the shader decompiler

### List of issues so far
- [x] Attempted swizzle on special function calls e.g sqrt https://github.com/RPCS3/rpcs3/issues/1894
- [ ] Failure to swizzle component result in vertex texture fetch https://github.com/RPCS3/rpcs3/issues/1890
- [x] Broken handling of ARL vector opcode https://github.com/RPCS3/rpcs3/issues/1913
- [x] Broken handling of DDX/DDY swizzle #https://github.com/RPCS3/rpcs3/issues/2002
- [x] Broken swizzle of some grouped functions e.g (fn).xyz #1989

**Comment by kd-11** [comment]
@DHrpcs3 Combined list here. Will add other issues as they are discovered

**Comment by DHrpcs3** [comment]
@kd-11, very cool! Thanks!

**Comment by kd-11** [comment]
Handling of ARL is not correct as well. On old decompiler, we can see:
```
	// Note: It looks like ARL opcode ignore input/output swizzle mask (SH3)
	case RSX_VEC_OPCODE_ARL: AddCode("$ifcond $awm = " + getIntTypeName(4) + "($0);");  break;
```

The new decompiler swizzles the cast. I have checked against a different game (G-Force) and it confirms the behaviour. Characters are stuck in T-Pose and examining the shader you can see access to fields that have been removed due to swizzling.  See https://github.com/RPCS3/rpcs3/issues/1913

**Comment by kd-11** [comment]
When running hatsune miku with latest decompiler, you get the following output:
```
r2.xy = dFdx(r2.zw).xyxy;
```
It would have been better to swizzle to dst after expanding to vec4

**Comment by kd-11** [comment]
Grouping does not take into account the dimensions of the function in the brackets: e.g
```
if (cc0.w > 0.0) r2.xyz = r0.xyz / (max(abs(r0.w), 1e-15) * sign(r0.w)).xyz;
```
The last .xyz is unnecessary. A better pattern training is required here. In fact for most operations against a non-vector, no swizzle is necessary.

**Comment by kd-11** [comment]
https://github.com/RPCS3/rsx_program_decompiler/pull/6 should fix the ignored swizzle disabled flag

**Comment by kd-11** [comment]
All fragment shader swizzle bugs were fixed here https://github.com/RPCS3/rsx_program_decompiler/pull/6
On to vertex shader stuff...
