### ISSUE TITLE
Qt Progress Tracking

### ISSUE THREAD

**Issue by flash-fire** [RPCS3/rpcs3#2711]
#This issue is to track progress towards converting RPCS3 to Qt. 

The [repo](https://github.com/flash-fire/rpcs3) for progress which uses the branch [RPCS3-QT](https://github.com/flash-fire/rpcs3/tree/RPCS3-QT). The [pull request](https://github.com/RPCS3/rpcs3/pull/2645). The [instructions to build ](https://github.com/flash-fire/rpcs3/blob/RPCS3-QT/README.md)are updated to reflect getting [Qt.](https://www.qt.io/)

Goals:

- [x] Make CMake/Appveyor work again. This also means fixing the Linux build to work with Qt. 
- [x] Create base/stub implementations for menus that are not yet implemented. There are many disabled menu options that could be finished.  Some are mimickable from wx, others are new and improvements.
- [x] Flesh out implementations for usability. Some main ones:

1.  <s>Debugger</s>
2.  <s>Logging</s>
3.  <s>Gamelist</s> (polishing needed)

- [x] Have state be consistent.  Implement the YAML stuff.

- [x] Connect things to backend so the UI isn't just pretty, it is functional.  This is a per item basis.  And, listing all things that need/have implementation would be cumbersome (though I may do so anyhow).  The best bet would be to look at the code and comment here/ask on discord.

Known Bugs (from build testing):

<s>1) If you cancel a package installation, the taskbar progress won't reset. (thanks ssshadow)</s>
2) Qt is a bit zealous in its copying of dll dependencies (windowdeployqt.exe). Figure out which dlls are actually needed.
<s>3) Add SPU checkboxes in Core (I'll need to merge with master and it should be good)</s>
<s>4) Fix initial column sizes (Fixed but needs to get merged in still) </s>
<s>.5) GuiConfig is in a weird spot. (../bin/GuiConfig)  That's because I copied the MSVC build to make custom build.  Appveyor will have a different defined location, and it should be fine.</s>
<s>6) Autosaves are broken.</s>

**Comment by Megamouse** [comment]
https://github.com/Megamouse/WIP-List-for-Qt-Build/issues/3

My lists for the stuff I'm working on

**Comment by flash-fire** [comment]
Logging is done except for having the log settings persist through reset.

**Comment by flash-fire** [comment]
Fix emu stop on close is done. (I cant modify the list. Sad)

**Comment by AniLeo** [comment]
View defaults to
![image](https://cloud.githubusercontent.com/assets/10283761/26267181/afd84a9a-3ce0-11e7-8c73-f3330bb16fe9.png)

And even expanded Ni no Kuni takes a bunch of space
![image](https://cloud.githubusercontent.com/assets/10283761/26267211/c97ebf92-3ce0-11e7-8725-3503977376a9.png)

**Comment by raveskirza** [comment]
Tried it with the custom build of flash-fire

It looks like it is unable to create a new Save Data
![image](https://cloud.githubusercontent.com/assets/28158623/26277286/a2ccf314-3d53-11e7-8ff8-bed321eae56c.png)

When there is a Save Data already available. The below dialog OK button does not seem to respond
![image](https://cloud.githubusercontent.com/assets/28158623/26277387/23c24ed8-3d54-11e7-86eb-305bd7053a7f.png)

**Comment by flash-fire** [comment]
Just noting I've seen these, thanks for looking at this!

**Comment by CesarAxe** [comment]
The dialog OK button not respond to install the game data.
![datosdeljuego](https://cloud.githubusercontent.com/assets/17837481/26282526/b27b505a-3dd8-11e7-9d60-1d8585330b7c.PNG)

**Comment by bobthecooldad** [comment]
Bioshock
- Crash on load - White screen
https://pastebin.com/neDJgWAD
F {rsx::thread} : class std::logic_error thrown: fs::file is null

Simpsons Game
-F {rsx::thread} : class std::logic_error thrown: fs::file is null

Lego Dimentions
-F {rsx::thread} : class std::logic_error thrown: fs::file is null

**Comment by raveskirza** [comment]
F {rsx::thread} : class std::logic_error thrown: fs::file is null

This happens if your D3D adapter is not selected correctly. Sems like the first time QT does not set it correctly
try to change the adapter to OpenGL. Run a game
Now change the adapter to D3D12.
This is how I resolved it. Maybe the first time D3D adapter value is not getting updated properly in the config.yml

**Comment by flash-fire** [comment]
Build updated! @raveskirza thanks for the detailed report that made fixing this bug a lot easier!

(this will be much easier once appveyor is fixed, but fixing appveyor is beyond my skills)

**Comment by Megamouse** [comment]
@raveskirza @CesarAxe  please test again with the new build

**Comment by CesarAxe** [comment]
@Megamouse Now it works, thanks.

**Comment by flash-fire** [comment]
Updated build to reflect vfs not working and a couple other small changes. (pretend I am a human appveyor lol)

**Comment by raveskirza** [comment]
AutoSave dialog now work nicely with the new build 6

However the issue with the D3D adapter still exist
When configuring RPCS3 the first time, it displays that  D3D adapter is not available
![image](https://cloud.githubusercontent.com/assets/28158623/26330820/d0b7449a-3f1b-11e7-80ef-76091029c163.png)

But in the setting, however it would show as it has been set
![image](https://cloud.githubusercontent.com/assets/28158623/26330866/1386effa-3f1c-11e7-8d94-4abbe18f0acd.png)

When a game is booted,it will throw the error message as 
F {rsx::thread} : class std::logic_error thrown: fs::file is null

![image](https://cloud.githubusercontent.com/assets/28158623/26330923/4e3f3738-3f1c-11e7-849a-9639f6bb0e4a.png)

Config also looks fine
![image](https://cloud.githubusercontent.com/assets/28158623/26330934/64c379a6-3f1c-11e7-8f2f-c044f5fc0780.png)

To resolve
We have to change the Graphics to OpenGL or Vulkan, start a Game, then close the game
Then go back to setting and change to D3D adapter. this time D3d can be used to Boot the game

If you look at the config, It is still the same as it was before but how it starts working for D3D after performing the above two steps is quite puzzling
![image](https://cloud.githubusercontent.com/assets/28158623/26331346/76ec6e74-3f1e-11e7-96e5-5d295616d29e.png)

**Comment by raveskirza** [comment]
Related to keyboard mapping

When the config.yml from the wx rpcs3 is copied to the rpcs3qt. I see the below discrepancy

wX:

![image](https://cloud.githubusercontent.com/assets/28158623/26331532/69f3c39c-3f1f-11e7-8fc7-11ee4fb7a7cc.png)

![image](https://cloud.githubusercontent.com/assets/28158623/26331569/a5be10b2-3f1f-11e7-9b17-d643830f601b.png)

QT (It automatically changes the keyboard mapping without any inputs from us)

![image](https://cloud.githubusercontent.com/assets/28158623/26331594/bfbbd08a-3f1f-11e7-9a4c-25cf5eb67001.png)

![image](https://cloud.githubusercontent.com/assets/28158623/26331620/e4b29bbc-3f1f-11e7-9277-56087c93ea68.png)

**Comment by flash-fire** [comment]
Yeah. The keybindings are different inside of Qt, and maintaining a map from WX keys to Qt keys isn't worth the effort for reverse compatibility. It's best just to wipe the old file to defaults because they aren't compatible in general.

**Comment by Nekotekina** [comment]
It's slightly incorrect. I would recommend to create another file, and leave wx stuff unchanged. This would be more consistent.

**Comment by flash-fire** [comment]
Alright. I'll modify to make and use a new file.

**Comment by Megamouse** [comment]
@raveskirza the Warning you get in the log only happens if no valid adapter is set, which is the case on first start. The bug you refer to seems to be unrelated to the code, but to some other ominous problem.
That said however, the search for this bug lead us to another one, which caused the Warning I talked about before to be spawned every time.  It was caused by not getting valid strings for the adapter from config.yml. this should be fixed soon. Hopefully we find the bigger problem soon.
If you put the newly unzipped qt files into a completely new rpcs3 master folder, the phenomenon should not occur.

**Comment by flash-fire** [comment]
Latest build (8) should fix both keyboard file name being same as wx and direct X error. Please retest. @raveskirza

**Comment by raveskirza** [comment]
@flash-fire, @Megamouse, great work! Now it is smooth as silk

I noticed a  very minor difference in behavior between wx and qt  Settings , load Libraries section, Manual library selection list.

Steps to replicate:
a. Search for a module which is currently not selected e.g. fiber
b. Select the module e.g libfiber.sprx
c. Now clear the search string, so that all the modules are displayed
d. wx: the select module will appear on the top, you dont have to scroll down the list to see if the module is selected
qt: the select module will not appear on the top, you will need to scroll down the list to see if the module is selected. If you click OK and then again open the settings, it appears at the top though.

**Comment by Megamouse** [comment]
@raveskirza could you retest the library? 
https://ci.appveyor.com/project/rpcs3/rpcs3/build/0.0.2-4731/artifacts

**Comment by raveskirza** [comment]
Tried the below latest build and library list behavior is exactly like it was in wx. Nice!
https://ci.appveyor.com/api/buildjobs/aoqfmodu1309af2j/artifacts/rpcs3-v0.0.2-2017-05-25-51b0a63e_win64.zip

**Comment by AniLeo** [comment]
#2645 merged
