### ISSUE TITLE
D3D12 Issues

### ISSUE THREAD

**Issue by kd-11** [RPCS3/rpcs3#2896]
A tracker with DX12-only issues consolidated here.
- [ ] Saint Seiya Crash https://github.com/RPCS3/rpcs3/issues/2589
- [ ] Street fighter 2 Turbo HD https://github.com/RPCS3/rpcs3/issues/2583
- [ ] Limbo issue https://github.com/RPCS3/rpcs3/issues/2451
- [ ] Ring buffer overflow https://github.com/RPCS3/rpcs3/issues/2413
- [ ] Error reporting conversion issue https://github.com/RPCS3/rpcs3/issues/2371
- [ ] Aspect ratio https://github.com/RPCS3/rpcs3/issues/2187
- [ ] Stencil reflect https://github.com/RPCS3/rpcs3/issues/2164
- [ ] Soul Calibur https://github.com/RPCS3/rpcs3/issues/2131
- [ ] Invalid parameter crash https://github.com/RPCS3/rpcs3/issues/2109
- [ ] Blade Arcus https://github.com/RPCS3/rpcs3/issues/2051
- [ ] Saint Seiya Shader https://github.com/RPCS3/rpcs3/issues/2050
- [ ] Worms https://github.com/RPCS3/rpcs3/issues/2049
- [ ] Bayonetta https://github.com/RPCS3/rpcs3/issues/2046
- [ ] PDF https://github.com/RPCS3/rpcs3/issues/1954
- [ ] Vertex texturing https://github.com/RPCS3/rpcs3/issues/1842
- [ ] Way of the Samurai https://github.com/RPCS3/rpcs3/issues/1805
- [ ] Cube MRT sample https://github.com/RPCS3/rpcs3/issues/1774
- [ ] Shader compilation bug https://github.com/RPCS3/rpcs3/issues/1771
- [ ] Final Fight https://github.com/RPCS3/rpcs3/issues/1410
- [ ] Super Frog https://github.com/RPCS3/rpcs3/issues/1381
- [ ] Naruto shadows https://github.com/RPCS3/rpcs3/issues/1949
- [ ] Buffer Synchronization does not work
- [ ] Ni no Kuni https://github.com/RPCS3/rpcs3/issues/2465

Most of these are caused by one synchronization bug and several others from broken optimization paths. The renderer needs a rewrite to properly solve these.

**Comment by YaPeL** [comment]
just throw it to the trash and focus on vulkan/ogl

**Comment by Uramekus** [comment]
a sincere question, how d3d12 is important by any means?
i know it has good debugging tools like pix for windows 
but ignoring that, why it would be relevant?

**Comment by woj1993** [comment]
@Uramekus 
- DX12 can be used in Nvidia Fermi family card while Vulcan is not supported.
- DX12 will be good alternative to Vulcan in future.
- DX12 has good debug tools as you say.

**Comment by Zangetsu38** [comment]
Naruto and Saint Seiya error have changed.
>F {rsx::thread} class std::runtime_error thrown: HRESULT = D3D12 device was removed with error status 0x887A0001
(in file h:\git\rpcs3-dante\rpcs3\emu\rsx\d3d12\D3D12MemoryHelpers.h:39)

**Comment by Zangetsu38** [comment]
Add todo for Ni no kuni

**Comment by aakh1361** [comment]
Farcry Classic  [NPEB00989]
> F {rsx::thread} class std::runtime_error thrown: HRESULT = D3D12 device was removed with error status 0x887A0001
(in file Emu\RSX\D3D12\D3D12GSRender.cpp:664)

**Comment by darkdragonP** [comment]
d3d12 error
F {rsx::thread} class std::runtime_error thrown: fragment program compilation failure (in file c:\projects\rpcs3\rpcs3\emu\rsx\d3d12\D3D12PipelineState.h:162)

Project diva not starting... error

**Comment by kd-11** [comment]
Closing as D3D12 is no longer supported.
