### ISSUE TITLE
GL/VK: Tekken Tag Tournament 2 - Graphics rendering issues

### ISSUE THREAD

**Issue by raveskirza** [RPCS3/rpcs3#3785]
- [x] Black or distorted graphics in Vulkan (Fixed in #4469 )
- [x] Green overlay in OpenGL (Fixed in #4469) 
- [x]  Half screen bug in two last stages, Affects both Vulkan & OpenGL(Fixed in #4698)

There are some stages that are not rendered properly in Vulkan. 
OpenGL seems to render those stages properly but with a green overlay(#3031)

**Vulkan Render Docs:**
![image](https://user-images.githubusercontent.com/28158623/33243818-e6c4be6a-d2ba-11e7-904e-e146587a9227.png)

https://mega.nz/#!Zpx0VayQ!W3yjwzpNqCCvVMEEKzHXB4fI_VuKKJHMZQ1J6FcNbok

![image](https://user-images.githubusercontent.com/28158623/33243828-ffdb4914-d2ba-11e7-86d5-23ed412255c2.png)

https://mega.nz/#!N4AnXYpa!3qmB_nlZXZJGKvskjyJlWYOGdGvXYj8jR25ESrXwpYU

**Corresponding OpenGL Render Docs:**
https://mega.nz/#!NwBXWJxR!oUAD-K3mOr7K24T3pV55J1z_Jes9Y7k10kELAYMxj00
https://mega.nz/#!o1xiHBgB!GT3O8Wc36teE5ejNFqTzZEAvcSatxmfh1cHI2-0DiGE

There are couple of stages that is not rendered properly by OpenGL(split graphics) but vulkan looks good enough. I will capture the renderdoc if the game reaches that area.

E: Adding GPU Info and screenshots for vulkan(as per VelocityRa). OpenGL screenshots for game can be referred from the Github issue
nVidia 1050
388.00

**Comment by VelocityRa** [comment]
From the RenderDoc documentation:
>RenderDoc captures are not currently portable between machines unless their hardware/driver configuration is almost identical.

And indeed, trying to open the Vulkan logs crashes RenderDoc. So I'm not sure if supplying logs yourself is useful, at least for Vulkan.

**Comment by kd-11** [comment]
Retest

**Comment by raveskirza** [comment]
No change

**Comment by MarioSonic2987** [comment]
Tested in https://github.com/RPCS3/rpcs3/commit/ec0cd9f006b748056d62480a133f74097fd76e12:

Characters' outfits are colored incorrectly. This stage has a half screen bug.
![image](https://user-images.githubusercontent.com/20027681/36968943-50cb78ca-2064-11e8-972c-c26590db6f5b.png)

When you pause the game, it's fine.
![image](https://user-images.githubusercontent.com/20027681/36968988-746f00ee-2064-11e8-82e0-1bfaba258a73.png)

In this stage and others, it has the green overlay:
![image](https://user-images.githubusercontent.com/20027681/36969054-b3f29834-2064-11e8-9932-adff531ae78d.png)

In Vulkan, Jin is visible in the half screen bug position, but his textures are acting weird.
![image](https://user-images.githubusercontent.com/20027681/36969442-c73e2c36-2065-11e8-8d70-8ed1e9dd9042.png)

This stage is almost invisible in Vulkan (same issue as Grid 1):
![image](https://user-images.githubusercontent.com/20027681/36969561-1f1c6a62-2066-11e8-8883-e248b1fbe418.png)

Lee's outfit has cut colors, same with all characters:
![image](https://user-images.githubusercontent.com/20027681/36969669-7da2408e-2066-11e8-9ff4-b85c99c54ac0.png)


[Log OpenGL](https://github.com/RPCS3/rpcs3/files/1780358/Log.TTT2.5-3-18.GL.gz)
[Log Vulkan](https://github.com/RPCS3/rpcs3/files/1780395/Log.TTT2.5-3-18.VK.gz)
[Shaderlog](https://drive.google.com/open?id=1q-RXQ0F2p5iaXP1DiLz4MD0l4DduAkIS)
[RenderDoc OpenGL](https://drive.google.com/open?id=1cOiZn4TRZ1-VtwJByNiQxjnWVgD-cjoQ)

**Comment by raveskirza** [comment]
The vulkan issues fixed by #4469 . 
Half screen issue still present for Open GL and Vulkan for some stages.

**Comment by toccata10** [comment]
I saw it advertised as playable on Youtube, but I still have some serious graphical problems.
Config: ArchLinux, r9 fury, mesa 18.1.4. Tested on Linux. Tested the saudi aradia stage on windows+nvidia too: same problems.
saudi arabia: characters are invisible (except when stopped by start button): stage not playable without srm.
Other stages (excepted last 2 which don't work without srm) need wcb otherwise, they are too bright.
![selection_027](https://user-images.githubusercontent.com/7478580/42768420-c32603c6-891f-11e8-89e6-2242e6a07159.jpg)
![selection_029](https://user-images.githubusercontent.com/7478580/42768423-c4a6a624-891f-11e8-80c6-a27dfdc9eee8.jpg)
![selection_030](https://user-images.githubusercontent.com/7478580/42768425-c60df1ac-891f-11e8-9103-aba0e0c4cd6d.jpg)
With srm, the image quality is really poor.
