### ISSUE TITLE
GL/Vulkan: Ratchet & Clank 1/2/3/Gladiator graphical issues

### ISSUE THREAD

**Issue by MarioSonic2987** [RPCS3/rpcs3#3846]
Tested in https://github.com/RPCS3/rpcs3/commit/bfb3144f3476d1367da0fd9012e6475a0e6b9603.

**Common issues**:

- [x] Flickering texture in maps - Fixed in #4162
- [x] Color issue in text - Fixed in #5047 
- [x] Square shadows - Fixed in #4312
- [x] No darkened background in pause menu - Fixed in #5047 
- [x] Broken fade-out transition - Fixed in #5047 

![image](https://user-images.githubusercontent.com/20027681/33557922-e1faaf58-d908-11e7-88ea-e82cd4f69b1f.png)
![image](https://user-images.githubusercontent.com/20027681/33555996-c619c946-d902-11e7-9985-4e5d9e1d2d81.png)
![image](https://user-images.githubusercontent.com/20027681/33556244-868d8226-d903-11e7-844e-54340d290cb9.png)
![image](https://user-images.githubusercontent.com/20027681/33558231-a0a69f66-d909-11e7-8d78-e50f2e22daf2.png)
![image](https://user-images.githubusercontent.com/20027681/33558040-39b32e8c-d909-11e7-95f4-4f4f0d8c6f6b.png)
![image](https://user-images.githubusercontent.com/20027681/33556162-49a15554-d903-11e7-872c-d6309afaa58f.png)

[Log OpenGL](https://github.com/RPCS3/rpcs3/files/1527545/Log.RC1.4-12-17.GL.gz)
[Shaderlog OpenGL/Vulkan ](https://drive.google.com/open?id=1ydvjYgklfY4F4EEOGrDqLYRThjnpBaOX)
[RenderDoc OpenGL](https://drive.google.com/open?id=1fAUXjX2Ceavk82aYNMk7gn_MSKhXNDnB)

Log, Shaderlog and RenderDoc's traces are from R&C1 only, because the other games use the same engine.

**Comment by Asinin3** [comment]
I'm not sure about 1-3 but deadlocked needed me to lower resolution threshold for minimap and some text to display properly, so if you do run into any issue like that then try lowering threshold. (I just used 1x1)

**Comment by MarioSonic2987** [comment]
@Asinin3 I didn't use Resolution Scaling.

**Comment by ismailawadat** [comment]
[shaderlog.zip](https://github.com/RPCS3/rpcs3/files/1544414/shaderlog.zip)
hello sir 
can you help me with GOW3 RPCS3 not working i have laptop with two graphic cards

**Comment by Gamedev1909** [comment]
@ismailawadat wrong thread man

**Comment by MarioSonic2987** [comment]
Fixed flickering textures in #4162:
![image](https://user-images.githubusercontent.com/20027681/36310561-c7e97cfc-1328-11e8-9bd0-74ec8add7fa2.png)
![image](https://user-images.githubusercontent.com/20027681/36310701-32209c7c-1329-11e8-8e45-dfd5ec8089a8.png)
![image](https://user-images.githubusercontent.com/20027681/36310781-65e25f32-1329-11e8-8150-5e358aa7eea9.png)

**Comment by MarioSonic2987** [comment]
![image](https://user-images.githubusercontent.com/20027681/36393766-42c779bc-15b1-11e8-953b-c31e8f1f97fb.png)
![image](https://user-images.githubusercontent.com/20027681/36393834-9711aa2e-15b1-11e8-9155-248736fa4c59.png)
[Log RC3 19-2-18 GL.gz](https://github.com/RPCS3/rpcs3/files/1737954/Log.RC3.19-2-18.GL.gz)
[Shaderlog OpenGL (R&C 3)](https://drive.google.com/open?id=1u_FozN4Hes-g0BQF0TrSdjyYRCuOsT1f)
[RenderDoc OpenGL (R&C 3)](https://drive.google.com/open?id=1XzPdZ3G1LdjNEYGKWlL7vtBocRHcJdhA)

**Comment by MarioSonic2987** [comment]
Screen turns blue when you use certain weapons or increase health (R&C2), shortly after, goes to normal. Same with R&C3. It's always there.
![image](https://user-images.githubusercontent.com/20027681/37868230-95f160f6-2fa3-11e8-9aa9-25b0dc113ba8.png)

**Comment by MarioSonic2987** [comment]
With #5047, fixes wrong font colour, missing darkened background in pause menu and broken fade-in and fade-out transitions in all R&C PS2 games:
![image](https://user-images.githubusercontent.com/20027681/44995232-7490a780-afa2-11e8-9e44-4011aef0cf58.png)
![image](https://user-images.githubusercontent.com/20027681/44995180-28456780-afa2-11e8-9f20-d98b4d92367a.png)
![image](https://user-images.githubusercontent.com/20027681/44995281-ae61ae00-afa2-11e8-98b6-71f4aac953df.png)

These games are now visually correct. Only remains low performance in many areas. Closing this issue.
