### ISSUE TITLE
macOS Meta Issue

### ISSUE THREAD

**Issue by hcorion** [RPCS3/rpcs3#5361]
Here is a list of the issues that need to get fixed before we can start providing binaries for MacOS:

- [x] Fix SIGBUS crashes that happen to every commercial game
- [x] Fix LLVM on MacOS.

Some of the issues that can be solved afterwards:
- [x] macOS supported controller backend
- [x] better audio API than OpenAL for macOS.

**Comment by kvark** [comment]
@hcorion I just tried building RPCS3 afresh on macOS and running some simple things, like Scogger HD (installed from .pkg) and getting PPU unhandled exceptions right away on start. Is this expected or related to some of the things listed here? If not, I'll investigate further and file issues separately.

**Comment by bitsydarel** [comment]
Hi, any updates on this ?

**Comment by 13xforever** [comment]
hcorion is currently busy irl with the education and isn't available, generally speaking.

**Comment by gabjauf** [comment]
Hello guys,

Have you got any update on the binary status for macOS?
I tried to compile rpcs3 on my Mac but it does not seem to be working for the moment.
I tried the CI script and a custom script on my own.

Vulkan seems to be "working" now (well at least, cmake can find it)

My script 😛:
```cmake ../rpcs3/ -DQt5_DIR=$(brew --prefix qt5)/lib/cmake/Qt5 -DWITH_LLVM=OFF -DCMAKE_C_COMPILER=/usr/local/bin/gcc-9 -DCMAKE_CXX_COMPILER=/usr/local/bin/g++-9 -DUSE_NATIVE_INSTRUCTIONS=OFF -G Ninja && ninja```

Tried with clang as well (got some different errors 😝 )

I am not really an expert in Cpp and cmake stuff but with some guidance, I may be able to make it work.
I will try to provide compiling errors as much as I can meanwhile 😉

**Comment by gabjauf** [comment]
<img width="691" alt="Capture d’écran 2020-11-21 à 17 28 25" src="https://user-images.githubusercontent.com/17923230/99882195-f79f8600-2c1e-11eb-862e-d4f379a6b8ce.png">

**Comment by gabjauf** [comment]
(this one is from a 3rd party lib)

**Comment by AniLeo** [comment]
There has been no progress, in fact the Apple code paths may eventually be purged from the code base as Apple moves away from x86

**Comment by iMonZ** [comment]
macOS's support could be provided by using MoltenVK.

Additionally, the Zink tool can be added for macOS and Linux.

**Comment by dio-gh** [comment]
[Zink](https://docs.mesa3d.org/drivers/zink.html) is an OpenGL implementation over Vulkan, but since we have a decently maintained native OpenGL renderer, I'm fully certain that a Zink backend would not give any benefits, especially on Mac, where Zink targets MoltenVK.

As for MoltenVK, I remember some technical limitations being blockers, but #4996 seemed to have gone peachy, so I'm unsure where it stands now. Maybe someone with an x86 Mac can tell us if the emulator even compiles these days?

Please also consider that Apple is transitioning away to ARM, full force. Mac support would need not just compliance with MoltenVK, but also adjustments made to the recompilers, as despite them technically using LLVM as a backend, as far as I'm aware, lots of x86isms are present in it.

These, along with the highly limited access to Mac hardware, the minimal developer interest, and general hostility Apple seems to be showing against emulators within some spaces of their ecosystem makes them quite a hard sell at the moment for anyone involved.

**Comment by malicious** [comment]
Tried compiling `v0.0.18` on an x86 mac, dependencies seem fine + stuck on rpcs3:

```Consolidate compiler generated dependencies of target rpcs3_emu
[ 78%] Building CXX object rpcs3/Emu/CMakeFiles/rpcs3_emu.dir/cache_utils.cpp.o
warning: unknown warning option '-Wdeprecated-copy'; did you mean '-Wdeprecated'?
      [-Wunknown-warning-option]
In file included from [snip]/rpcs3/rpcs3/Emu/cache_utils.cpp:1:
In file included from [snip]/rpcs3/rpcs3/stdafx.h:3:
[snip]/rpcs3/rpcs3/util/types.hpp:529:11: error: unknown type name
      'UnsignedInt'
template <UnsignedInt T>
          ^
```

Related changes seem to be from 2021-05-22, which isn't too long ago (#4996 is three years ago now)

**Comment by f2re** [comment]
Im tried compiling `v0.0.19` on MacOS `10.15.7` and have some error:
```
[ 70%] Built target LLVMX86AsmParser
Scanning dependencies of target rpcs3_emu
[ 70%] Building CXX object rpcs3/Emu/CMakeFiles/rpcs3_emu.dir/cache_utils.cpp.o
warning: unknown warning option '-Wdeprecated-copy'; did you mean '-Wdeprecated'? [-Wunknown-warning-option]
In file included from /Users/meteo/Downloads/rpcs3/rpcs3/Emu/cache_utils.cpp:1:
In file included from /Users/meteo/Downloads/rpcs3/rpcs3/stdafx.h:3:
/Users/meteo/Downloads/rpcs3/rpcs3/util/types.hpp:531:11: error: unknown type name 'UnsignedInt'
template <UnsignedInt T>
```

**Comment by iMonZ** [comment]
Could it be that you are using the wrong compiler?

**Comment by f2re** [comment]
no, Im using `gcc-11` and `g++-11`, is it wrong version?

**Comment by nastys** [comment]
Try building the rmacs3 branch of my fork with
```zsh
export Qt5_DIR="/usr/local/Cellar/qt@5/5.15.2_1/lib/cmake/Qt5"
export CXX=g++-11
export CC=gcc-11
cmake -DUSE_DISCORD_RPC=OFF -DUSE_VULKAN=ON -DUSE_ALSA=OFF -DUSE_PULSE=OFF ../rpcs3/ && make -j8```
(Vulkan SDK, molten-vk, and vulkan-headers are required for Vulkan support)

LLVM still doesn't work, though (see #11222).

**Comment by iMonZ** [comment]
I would love to see a HomeBrew Formula :)

**Comment by f2re** [comment]
> Try building the rmacs3 branch of my fork with

Thanks, so Im go to next error =)
```
[ 57%] Building C object 3rdparty/libusb/CMakeFiles/usb-1.0-static.dir/libusb/libusb/os/darwin_usb.c.o
/Users/meteo/Downloads/rpcs3/3rdparty/libusb/libusb/libusb/os/darwin_usb.c: In function 'darwin_handle_transfer_completion':
/Users/meteo/Downloads/rpcs3/3rdparty/libusb/libusb/libusb/os/darwin_usb.c:2151:3: error: variable-sized object may not be initialized
 2151 |   const char *transfer_types[max_transfer_type + 1] = {"control", "isoc", "bulk", "interrupt", "bulk-stream"};
      |   ^~~~~
make[2]: *** [3rdparty/libusb/CMakeFiles/usb-1.0-static.dir/libusb/libusb/os/darwin_usb.c.o] Error 1
```

> I would love to see a HomeBrew Formula :)

something like that?

```
brew install molten-vk vulkan-headers sdl2
```

**Comment by nastys** [comment]
> Thanks, so Im go to next error =)
> 
> ```
> [ 57%] Building C object 3rdparty/libusb/CMakeFiles/usb-1.0-static.dir/libusb/libusb/os/darwin_usb.c.o
> /Users/meteo/Downloads/rpcs3/3rdparty/libusb/libusb/libusb/os/darwin_usb.c: In function 'darwin_handle_transfer_completion':
> /Users/meteo/Downloads/rpcs3/3rdparty/libusb/libusb/libusb/os/darwin_usb.c:2151:3: error: variable-sized object may not be initialized
>  2151 |   const char *transfer_types[max_transfer_type + 1] = {"control", "isoc", "bulk", "interrupt", "bulk-stream"};
>       |   ^~~~~
> make[2]: *** [3rdparty/libusb/CMakeFiles/usb-1.0-static.dir/libusb/libusb/os/darwin_usb.c.o] Error 1
> ```

In 3rdparty/libusb/libusb/libusb/os/darwin_usb.c:2151, remove ``max_transfer_type + 1``.

**Comment by f2re** [comment]
So, go next =)
```
Scanning dependencies of target rpcs3_emu
[ 71%] Building CXX object rpcs3/Emu/CMakeFiles/rpcs3_emu.dir/cache_utils.cpp.o
g++-11: error: unrecognized command-line option '-stdlib=libc++'
```

**Comment by nastys** [comment]
That should be comment out in my fork. Are you sure you checked out the rmacs3 branch?

**Comment by f2re** [comment]
>Are you sure you checked out the rmacs3 branch?

Yeah, 🤦 Im on master branch.

**Comment by f2re** [comment]
So, when I'm about to finish, I get a QT error:

```
[ 96%] Building CXX object rpcs3/rpcs3qt/CMakeFiles/rpcs3_ui.dir/pad_settings_dialog.cpp.o
/Users/meteo/Downloads/rpcs3/rpcs3/rpcs3qt/main_window.cpp: In member function 'bool main_window::Init(bool)':
/Users/meteo/Downloads/rpcs3/rpcs3/rpcs3qt/main_window.cpp:96:29: warning: unused parameter 'with_cli_boot' [-Wunused-parameter]
   96 | bool main_window::Init(bool with_cli_boot)
      |                        ~~~~~^~~~~~~~~~~~~
In file included from /usr/local/Cellar/qt@5/5.15.2_1/lib/QtConcurrent.framework/Headers/qtconcurrentiteratekernel.h:49,
                 from /usr/local/Cellar/qt@5/5.15.2_1/lib/QtConcurrent.framework/Headers/qtconcurrentfilterkernel.h:47,
                 from /usr/local/Cellar/qt@5/5.15.2_1/lib/QtConcurrent.framework/Headers/qtconcurrentfilter.h:47,
                 from /usr/local/Cellar/qt@5/5.15.2_1/lib/QtConcurrent.framework/Headers/QtConcurrent:8,
                 from /Users/meteo/Downloads/rpcs3/rpcs3/rpcs3qt/game_list_frame.cpp:33:
/usr/local/Cellar/qt@5/5.15.2_1/lib/QtConcurrent.framework/Headers/qtconcurrentthreadengine.h:250:50: error: invalid declarator before '*' token
  250 |     ThreadEngineStarter<void>(ThreadEngine<void> *_threadEngine)
      |                                                  ^
/usr/local/Cellar/qt@5/5.15.2_1/lib/QtConcurrent.framework/Headers/qtconcurrentthreadengine.h:250:49: error: expected ')' before '*' token
  250 |     ThreadEngineStarter<void>(ThreadEngine<void> *_threadEngine)
      |                              ~                  ^~
      |                                                 )
```

[This](https://codereview.qt-project.org/c/qt/qtbase/+/339417) like seems as it alrready fixed, but in qt 6.1. Any ideas?

**Comment by nastys** [comment]
You need to replace those Qt headers (see #11222)

**Comment by f2re** [comment]
Thank you very much! Im dont know what I must doing to resolve nex (maybe last) problem:
```
[100%] Linking CXX executable ../bin/rpcs3.app/Contents/MacOS/rpcs3
ld: in /Users/meteo/Downloads/rpcs3/3rdparty/ffmpeg/macos/x86_64/libswscale.a(input.o), building for macOS, but linking in object file built for free standing,
collect2: error: ld returned 1 exit status
make[2]: *** [bin/rpcs3.app/Contents/MacOS/rpcs3] Error 1
make[1]: *** [rpcs3/CMakeFiles/rpcs3.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by nastys** [comment]
Oh, I forgot that you need to rebuild ffmpeg, replacing the existing .a files (no modifications to the source code are needed).

**Comment by f2re** [comment]
Hmm...now I have arch error by hidapi

```
[100%] Linking CXX executable ../bin/rpcs3.app/Contents/MacOS/rpcs3
Undefined symbols for architecture x86_64:
  "_NSAppKitVersionNumber", referenced from:
      _hid_init in libhidapi-mac.a(hid.c.o)
      _hid_enumerate in libhidapi-mac.a(hid.c.o)
      _hid_open_path in libhidapi-mac.a(hid.c.o)
ld: symbol(s) not found for architecture x86_64
```

**Comment by nastys** [comment]
[#issuecomment-986430965](https://github.com/RPCS3/rpcs3/issues/5361#issuecomment-986430965)

**Comment by gabjauf** [comment]
@f2re Did you manage to build it?

**Comment by f2re** [comment]
@gabjauf no, Im trying to fix hid.c problem.

**Comment by nastys** [comment]
See the edit in the message I linked

**Comment by f2re** [comment]
@nastys, @gabjauf thank you very much! It is work! =) e-e-e-e =)

**Comment by HerrHulaHoop** [comment]
I think some of the issues mentioned in the main issue is fixed. Maybe we can close this issue and @nastys can create a new meta issue to track the work that is still pending.
