### ISSUE TITLE
Surface configuration works inconsistently

### ISSUE THREAD

**Issue by kd-11** [RPCS3/rpcs3#9133]
"Ideal world conditions" are supposed to be perfect as far as emulation goes, but for some reason, games are negatively affected when they are enabled (WCB+WDB+RCB+RDB). This is because these options are rarely if ever used in combination by actual users so we don't see any bug reports for them. This is a tracker to get this issue solved.

# Work items
- [ ] Text is broken in madden series if RCB or WDB is enabled.

# Finally
- [ ] Merge RCB+RDB
- [ ] Merge WCB + WDB

Blocks https://github.com/RPCS3/rpcs3/pull/9107

**Comment by Satan86** [comment]
Car reflection on GT6 is broken with RCB enabled
![screenshot-2020_11_13_18_57_08](https://user-images.githubusercontent.com/61447828/99112850-15407000-25cd-11eb-9d5e-2bdc4fdcf9ae.png)

**Comment by kd-11** [comment]
That issue can be caused by using patches that affect movement of data (MLAA patch for example), not having the other data synchronization options enabled, or more likely the texture leakage mentioned in https://github.com/RPCS3/rpcs3/pull/9107. The reflection surface is detected as being corrupted and removed, so only black output is left.

**Comment by Caladain** [comment]
Would you like me to regress the games I have now (and in the future) with WCB+WDB+RCB+RDB in addition to the standard default config testing?

**Comment by kd-11** [comment]
That isn't necessary right now. I'll be doing some rewrites in a few weeks, you'll see an 'in progress' label on this ticket when that time comes. If you do want to test, you can still do so, but any bugs found must be reported here. Do not open separate issues for them.

**Comment by kd-11** [comment]
Merger of buffer options is done, but I first need to diagnose what is wrong with enabling both at the same time before that change can be merged. For anyone curious about testing https://github.com/RPCS3/rpcs3/pull/10119

**Comment by kd-11** [comment]
With current code, text in madden still disappears, but reappears and renders correctly after a short while. This disappearance still needs investigation as it shows that some data was lost even if temporarily. Root cause is as of yet unknown.

**Comment by kd-11** [comment]
ACiT shows vertex buffer corruption at the great clock, a sign that invalid overwrites are happening.

**Comment by kd-11** [comment]
ACiT bug is fixed with https://github.com/RPCS3/rpcs3/pull/10184

**Comment by kd-11** [comment]
Madden renders correctly with WCB+WDB (with my experimental branch https://github.com/RPCS3/rpcs3/pull/10119) but RCB still causes text to disappear. This issue seems to be caused by something different.

**Comment by kd-11** [comment]
https://github.com/RPCS3/rpcs3/issues/10208 Documents the cause of the strange visual bugs observed in some games and tracks the implementation as well.

**Comment by kd-11** [comment]
Finally figured out the final piece of the puzzle. I'll need to improve communication between the surface and texture caches which are unfortunately separate due to historical reasons.

**Comment by Darkhost1999** [comment]
I don't know where to report this or if it's of any interest until after Read buffers is enabled by default.
Far cry 4:
* Without read depth buffers.
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9438279/RPCS3.log)
* With read depth buffers.
·F 0:01:20.280478 {RSX [0x009b60c]} SIG: Thread terminated due to fatal error: Verification failed
(in file C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\rpcs3\Emu\RSX\VK\VKTexture.cpp:253[:4], in function copy_buffer_to_image) (error=0xcb)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9438285/RPCS3.log)

I'm testing "Ideal world conditions" among other tests to try to discover optimal settings for this game so far I believe Write color buffers, atomic FIFO accuracy, accurate rsx reservation access, and allow host gpu labels are needed.
However, the Read Depth buffers if enabled at all won't even get past the loading SPU cache screen into the Ubi logo.

**Comment by Darkhost1999** [comment]
To try the recommendation from VKTexture.cpp:253 and change resolution scale to 50% I get
E RSX: Blit request denied because the destination region does not fit! x10
F {SPU[0x0000100] Thread (Gear_ManagedCellSpursKernel0) [0x09a68]} SIG: Thread terminated due to fatal error: Assertion Failed! Vulkan API call failed with unrecoverable error: Device lost (Driver crashed with unspecified error or stopped responding and recovered) (VK_ERROR_DEVICE_LOST)
(in file C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\rpcs3\Emu\RSX\VK\vkutils\sync.cpp:214[:5], in function wait_for_event)
(in file C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\rpcs3\Emu\RSX\VK\vkutils\shared.cpp:107[:24], in function die_with_error)
[RPCS3.log](https://github.com/RPCS3/rpcs3/files/9438321/RPCS3.log)

**Comment by kd-11** [comment]
Thanks. Yes, report here if buffer options trigger bugs.

**Comment by Darkhost1999** [comment]
A piece of information for the
`// "Out of memory (compute heap). Lower your resolution scale setting."` error with the read depth buffers.
Raising the resolution scale works fine without issue. When using default resolution it fatal errors that code.
And only far cry 4 fatal errors with the other error at 50% resolution scale. Meanwhile far cry 3 works fine with errors about converting the image to the output size.

So this read depth buffer issue can go unobserved with people upscaling their game.
While downscaling just gives some can't fit the screen errors.

**Comment by Zackpunky** [comment]
hey there ! sorry to necro this thread but i noticed this issue in most madden games 
either black playfield or no texts 
is there a solution?

**Comment by kd-11** [comment]
There are solutions, but not something an end user can easily set up on their end. Most of the solutions will bring your fps down to single digits if you tried to enable developer debug build options. Just be a little patient. Progress has been made and I hope to have it out in the next few weeks before the year comes to an end.

**Comment by Triticum0** [comment]
#12946 Broken setting menu with WCB

**Comment by Ordinary205** [comment]
Enabling RCB causes extra graphical bug on Need for Speed The Run.

WCB
![Works](https://github.com/RPCS3/rpcs3/assets/125112932/8c12b788-aafa-40c4-a897-f1772e62b46a)

WCB+RCB
![Doesnt](https://github.com/RPCS3/rpcs3/assets/125112932/c6a3710c-45be-4d84-b2b8-5c53e5df7850)

WCB:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11522518/RPCS3.log.gz)

WCB+RCB:
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/11522515/RPCS3.log.gz)

This issue happens to all frostbite games.

**Comment by Darkhost1999** [comment]
> Thanks. Yes, report here if buffer options trigger bugs.

https://github.com/RPCS3/rpcs3/issues/7308#issuecomment-1046473292

**Comment by Triticum0** [comment]
enable WCB+RCB on pes 2014/15/16/17/18 causes graphical glitches
![NPUB90987_screenshot_2023_06_24_10_11_34](https://github.com/RPCS3/rpcs3/assets/71127352/fee60c09-3f7c-4d2c-8395-a90f1fb34d36)

Still an issue in latest build

**Comment by Darkhost1999** [comment]
> Thanks. Yes, report here if buffer options trigger bugs.

It seems that Write Color buffers causes more freezing in games prone to freezes than leaving the setting off.
Example games so far
- Oblivion (wcb fixes save icons)
- Skyrim (wcb fixes save icons) 
- Fallout 3 (wcb fixes save icons)
- Assassin's creed 3 (wcb + rcb fixes water)
- Assassin's creed 4 (wcb + rcb fixes water)
- Assassin's creed rogue (wcb + rcb fixes water)

I would say Dishonored also is more prone to freezes with wcb simply because accurate getllar recovers the freezes when wcb is disabled. But when enabled the freeze doesn't recover.
Frequently I test with accurate rsx reservation access or accurate gettlar to resolve freezing in these games because it often works. I suspect TSX would work too but I don't have a TSX enabled CPU.

I feel I can provide a couple logs for each of these games when they freeze. They each have varying durations but since they're prone to freezes anyways I can't guarantee the log will always contain a wcb issue rather than an issue elsewhere. Because this option alone isn't the isolated problem setting it is only the antagonist.

**Comment by kd-11** [comment]
> > Thanks. Yes, report here if buffer options trigger bugs.
> 
> It seems that Write Color buffers causes more freezing in games prone to freezes than leaving the setting off. Example games so far
> 
> * Oblivion (wcb fixes save icons)
> * Skyrim (wcb fixes save icons)
> * Fallout 3 (wcb fixes save icons)
> * Assassin's creed 3 (wcb + rcb fixes water)
> * Assassin's creed 4 (wcb + rcb fixes water)
> * Assassin's creed rogue (wcb + rcb fixes water)
> 
> I would say Dishonored also is more prone to freezes with wcb simply because accurate getllar recovers the freezes when wcb is disabled. But when enabled the freeze doesn't recover. Frequently I test with accurate rsx reservation access or accurate gettlar to resolve freezing in these games because it often works. I suspect TSX would work too but I don't have a TSX enabled CPU.
> 
> I feel I can provide a couple logs for each of these games when they freeze. They each have varying durations but since they're prone to freezes anyways I can't guarantee the log will always contain a wcb issue rather than an issue elsewhere. Because this option alone isn't the isolated problem setting it is only the antagonist.

https://github.com/RPCS3/rpcs3/pull/14907 should solve some of these issues.

**Comment by Ordinary205** [comment]
Sadly this doesn't fixes Assassin's Creed IV Black Flag when enabling WCB+RCB.
[RPCS3.log.gz](https://github.com/RPCS3/rpcs3/files/13699362/RPCS3.log.gz)
PPU Interpreter is still required.

**Comment by Darkhost1999** [comment]
The fix shouldn't have been to fix LLVM.
Assassin's Creed IV Black Flags with WCB on used to freeze before you could even get to the tutorial on how to fight. And if you were lucky to get past that it surely froze before you even got to the theater house.
But what should be tested is just how far can you go with WCB+RCB and ppu Interpreter without freezing. Technically it shouldn't freeze at all because when disabling wcb and rcb the game can be played plenty well and fine from the start all the way to Edward Kenway's island claiming it and beyond without freezing.

**Comment by Triticum0** [comment]
@kd-11 MotoGP08 seems to be fixed when RDB +WDB is enabled. you can tick the task on your tracker and maybe add pes 14/18 to the list?

**Comment by Triticum0** [comment]
Trash Panic seems to have an issue where with wcb on the lighting breaks when it tries to render a fire and smoke effect but with WCB+RCB the lighting fixed but breaks the fire effect.

WCB on
![NPUA70047_screenshot_2023_01_13_19_16_52](https://user-images.githubusercontent.com/71127352/212401947-c3f285a5-9c78-4309-b34f-2ffebc05837a.png)

WCB+RCB
![NPEA90042_screenshot_2024_01_03_01_19_52](https://github.com/RPCS3/rpcs3/assets/71127352/1eb4b28e-a0de-4b14-bb28-391f3230ea36)

**Comment by Triticum0** [comment]
#13432

**Comment by Triticum0** [comment]
Ratchet & Clank: All 4 One breaks when Turn on all the buffers.

**Comment by Triticum0** [comment]
Retested and there no change. Using other buffers + Cpu Blits breaks the lighting and shadows.
build (v0.0.30-15912-bc141831)

**Comment by Shoegzer** [comment]
In Fallout 3, turning on RCB+WCB produces graphical issues that are not present when only WCB is on.  More information including screenshot and log are available [here](https://github.com/RPCS3/rpcs3/issues/14862#issuecomment-1872430819)

**Comment by Linear524** [comment]
Hi KD-11 !
Just a small question - will you ever return on working remaining RSX issues ?

**Comment by kd-11** [comment]
@Linear524 Yes, I'm just busy with other things right now but I still plan on finishing all the items eventually.

**Comment by Darkhost1999** [comment]
> Thanks. Yes, report here if buffer options trigger bugs.

Kingdom Hearts 2.5 final mix flickers in the world map behind the commands list while read color buffers is enabled.

https://github.com/user-attachments/assets/0668edcd-f601-45d2-84ad-873708a4cd20

Possibly in combination with write color buffers. The entire map still has a flicker effect when flying around but that's a separate issue it seems.
Because it flickers and doesn't stay flashed I captured about 8 different rsx captures and none appear to have captured the issue. What's the best way to report issues that use more than 1 frame? Inform about game and let developer replicate issue?

**Comment by kd-11** [comment]
> > Thanks. Yes, report here if buffer options trigger bugs.
> 
> Kingdom Hearts 2.5 final mix flickers in the world map behind the commands list while read color buffers is enabled.
> 20251019-0127-56.3050978.mp4
> 
> Possibly in combination with write color buffers. The entire map still has a flicker effect when flying around but that's a separate issue it seems. Because it flickers and doesn't stay flashed I captured about 8 different rsx captures and none appear to have captured the issue. What's the best way to report issues that use more than 1 frame? Inform about game and let developer replicate issue?

If you go into the surface cache file, there is a debug flag that does not ship due to performance:
You probably need to enable this: https://github.com/RPCS3/rpcs3/blob/master/rpcs3/Emu/RSX/Common/surface_utils.h#L9

There are some other incomplete paths that lead to flickering such as pitch conversion but generally RCB/RDB flickers because we don't have any fast way to do fast (few microseconds) hashing of data that is several megabytes long. That may never be a reality so we either have to rethink how we do deferred writes or eliminate them altogether. This work is on hold during the restructuring as I don't want to repeat implementations for each backend separately.

**Comment by kd-11** [comment]
As for how to report these in a meaningful manner - the only way is with gfxreconstruct traces. However, that only works when the developer and the reporter have a GPU from the same family and I don't own RTX50 series card right now so that's not possible.
So for now just report, if I can't reproduce then it gets to sit around until I have hardware that can reproduce it.

**Comment by Darkhost1999** [comment]
I gave the flag a try and it dropped performance as indicated very low. Meanwhile the flicker for the entire map and for behind the commands hud was still there. There's also a very similar flicker every time toggling fullscreen mode where it's clear only in the top left corner square but the rest of the entire screen flashes a white foggy appearance. The slow speed possibly may enable me to capture the issue in an rsx capture as it appears to be at a set interval of how many frames until it flickers.
I have a turing gpu still as I haven't accomplished the goal to upgrade yet. I'll let you attempt to reproduce it or some other tester can aid if they share hardware with you.

**Comment by Triticum0** [comment]
You can ping me if kd needs any help as I have a 30 series gpu need a trace

**Comment by rleonever** [comment]
@kd-11 has this been fixed with the recent PRs?
